/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sharp_dev_exampleskdapp_CppProvider */

#ifndef _Included_net_sharp_dev_exampleskdapp_CppProvider
#define _Included_net_sharp_dev_exampleskdapp_CppProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sharp_dev_exampleskdapp_CppProvider
 * Method:    getCppString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sharp_1dev_exampleskdapp_CppProvider_getCppString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
